from .gradient import get_gradient,_test_get_gradient_distinct_config
from .sr import get_gradient_sr,_test_get_gradient_sr_distinct_config
from .sr_new import get_gradient_sr_new

from .amp_penalty import get_gradient_amp_penalty
from .amp_penalty_tri_tilde import get_gradient_amp_penalty_tri_tilde
from .amp_penalty_tri_tilde_linearsolve import get_gradient_amp_penalty_tri_tilde_linearsolve
from .amp_penalty_tri_tilde_netket import get_gradient_amp_penalty_tri_tilde_netket
from .amp_penalty_tri_tilde_linearsolve_epsilon import get_gradient_amp_penalty_tri_tilde_linearsolve_epsilon

from .minsr import get_gradient_minsr
from .minsr_tri_tilde import get_gradient_minsr_tri_tilde
from .minsr_tri_tilde_linearsolve import get_gradient_minsr_tri_tilde_linearsolve
from .minsr_tri_tilde_netket import get_gradient_minsr_tri_tilde_netket
from .minsr_tri_tilde_linearsolve_epsilon import get_gradient_minsr_tri_tilde_linearsolve_epsilon